### ISSUE TITLE
Enhance the index.html code 

### ISSUE THREAD

**Issue by fawzyeldev** [fawzyeltop/code#5]
### Enhance the index.html 
Please I'd like to enhance the index.html code asap

**Comment by drfawzyofficial** [comment]
Start now. I'm trusted in you :)

**Comment by fawzyeldev** [comment]
Thanks a lot for trusting me

**Comment by drfawzyofficial** [comment]
You are welcome, fawzyeldev and thanks a lot for the previous enhancements like "Readmefile, indexjs" Really you are an amazing contributor

**Comment by fawzyeldev** [comment]
You are welcome

**Comment by drfawzyofficial** [comment]
Let us start
